
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/dietfitness
spring.datasource.username=postgres
spring.datasource.password=jojo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

gemini.api.key=AQ.Ab8RN6KlCZ5pc0oTzugLb_uBjK3rrJfxcCfustjz_r8WF0YZQw
dietfitness.data.path=src/main/resources/data/data.json

app.jwt-secret=dietfitness-secret-2025-cameroun
app.base-url=http://192.168.3.145:8080

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
app.mail.from=ojoslath@gmail.com
spring.mail.username=ad0d3e001@smtp-brevo.com
spring.mail.password=xsmtpsib-aebcea4202a0525fa48aa3262fe346c6237b2db04be64491667f9a594e56d73f-uDtwoslx4HesxFQ7
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
